const mongoose = require('mongoose');

// 1. اتصال به دیتابیس
mongoose.connect('mongodb://127.0.0.1:27017/backend')

const db = mongoose.connection;

db.on('error', console.error.bind(console, 'connection error:'));
db.once('open', () => {
  console.log('✅ Connected to MongoDB successfully!');


  const userSchema = new mongoose.Schema({
    id: Number,
    fullName: String,
    phoneNumber: String,
    email: String,
    hasActiveSubscription: Boolean,
    signUpDate: Date,
    subscriptionExpireDate: Date,
    favoriteTitle: [String],
    country: String,
    city: String
  });

  const movieSchema = new mongoose.Schema({

    title: String,
    description: String,
    poster: String,
    videoUrl: String,
    rating: Number,
    topWeek: Boolean,
    genre: [String],
    year: Number,
    product: String,
    duration: Number
  });

  const User = mongoose.model('User', userSchema);
  const Movie = mongoose.model('Movie', movieSchema);


  const sampleUsers = [
    {

      "fullName": "محمد طاهری",
      "phoneNumber": "09123456789",
      "email": "mohammad.taheri@gmail.com",
      "hasActiveSubscription": true,
      "signUpDate": "2026-03-02",
      "subscriptionExpireDate": "2026-09-02",
      "favoriteTitle": ["آقازاده"],
      "country": "Iran",
      "city": "Ahvaz"
    },
    {

      "fullName": "الهام شریفی",
      "phoneNumber": "09123456790",
      "email": "elham.sharifi@gmail.com",
      "hasActiveSubscription": true,
      "signUpDate": "2026-02-14",
      "subscriptionExpireDate": "2026-08-14",
      "favoriteTitle": ["خاتون"],
      "country": "Iran",
      "city": "Kerman"
    },
    {

      "fullName": "پارسا اکبری",
      "phoneNumber": "09123456791",
      "email": "parsa.akbari@gmail.com",
      "hasActiveSubscription": false,
      "signUpDate": "2025-08-01",
      "subscriptionExpireDate": "2025-11-01",
      "favoriteTitle": ["در انتهای شب"],
      "country": "Iran",
      "city": "Yazd"
    },
    {

      "fullName": "نازنین رستمی",
      "phoneNumber": "09123456792",
      "email": "nazanin.rastami@gmail.com",
      "hasActiveSubscription": true,
      "signUpDate": "2026-01-05",
      "subscriptionExpireDate": "2026-07-05",
      "favoriteTitle": ["هیولا"],
      "country": "Iran",
      "city": "Urmia"
    },
    {
      "fullName": "کیان حسینی",
      "phoneNumber": "09123456793",
      "email": "kian.hosseini@gmail.com",
      "hasActiveSubscription": true,
      "signUpDate": "2026-04-07",
      "subscriptionExpireDate": "2026-10-07",
      "favoriteTitle": ["نوبت لیلی"],
      "country": "Iran",
      "city": "Hamedan"
    },
    {

      "fullName": "آرزو زمانی",
      "phoneNumber": "09123456794",
      "email": "arezoo.zamani@gmail.com",
      "hasActiveSubscription": false,
      "signUpDate": "2025-07-19",
      "subscriptionExpireDate": "2025-10-19",
      "favoriteTitle": ["جزیره"],
      "country": "Iran",
      "city": "Arak"
    },
    {

      "fullName": "میلاد کاظمی",
      "phoneNumber": "09123456795",
      "email": "milad.kazemi@gmail.com",
      "hasActiveSubscription": true,
      "signUpDate": "2026-03-11",
      "subscriptionExpireDate": "2026-09-11",
      "favoriteTitle": ["ساخت ایران"],
      "country": "Iran",
      "city": "Qazvin"
    },
    {

      "fullName": "فاطمه مرادی",
      "phoneNumber": "09123456796",
      "email": "fateme.moradi@gmail.com",
      "hasActiveSubscription": true,
      "signUpDate": "2026-02-01",
      "subscriptionExpireDate": "2026-08-01",
      "favoriteTitle": ["پدر گواردیولا"],
      "country": "Iran",
      "city": "Bandar Abbas"
    },
    {

      "fullName": "سامان فتحی",
      "phoneNumber": "09123456797",
      "email": "saman.fathi@gmail.com",
      "hasActiveSubscription": false,
      "signUpDate": "2025-06-14",
      "subscriptionExpireDate": "2025-09-14",
      "favoriteTitle": ["مهمونی"],
      "country": "Iran",
      "city": "Sanandaj"
    },
    {

      "fullName": "هلیا صادقی",
      "phoneNumber": "09123456798",
      "email": "helia.sadeghi@gmail.com",
      "hasActiveSubscription": true,
      "signUpDate": "2026-01-22",
      "subscriptionExpireDate": "2026-07-22",
      "favoriteTitle": ["عقرب عاشق"],
      "country": "Iran",
      "city": "Zanjan"
    },
    {

      "fullName": "بهنام نوری",
      "phoneNumber": "09123456799",
      "email": "behnam.nouri@gmail.com",
      "hasActiveSubscription": true,
      "signUpDate": "2026-04-09",
      "subscriptionExpireDate": "2026-10-09",
      "favoriteTitle": ["مانکن"],
      "country": "Iran",
      "city": "Gorgan"
    },
    {

      "fullName": "لیلا حیدری",
      "phoneNumber": "09123456800",
      "email": "leila.heydari@gmail.com",
      "hasActiveSubscription": false,
      "signUpDate": "2025-12-25",
      "subscriptionExpireDate": "2026-03-25",
      "favoriteTitle": ["داریوش"],
      "country": "Iran",
      "city": "Kish"
    }
  ]
    ;

  const sampleMovies = [
    {
      title: "The Shawshank Redemption",
      description: "داستان امید، آزادی و دوستی در یکی از بهترین زندان‌محورها.",
      poster: "/Images/movies/1.webp",
      videoUrl: "/Videos/1.mp4",
      rating: 9.8,
      topWeek: true,
      genre: ["Drama"],
      year: 1994,
      product: "IN",
      duration: 142,
    },
    {
      title: "The Godfather",
      description: "حماسه‌ای مافیایی درباره خانواده، قدرت و خیانت.",
      poster: "/Images/movies/2.webp",
      videoUrl: "/Videos/2.mp4",
      rating: 9.7,
      topWeek: true,
      genre: ["Crime", "Drama"],
      year: 1972,
      product: "IN",
      duration: 175,
    },
    {
      title: "The Dark Knight",
      description: "نبردی روان‌شناختی بین بتمن و جوکر.",
      poster: "/Images/movies/3.webp",
      videoUrl: "/Videos/3.mp4",
      rating: 9.5,
      topWeek: true,
      genre: ["Action", "Crime", "Drama"],
      year: 2008,
      product: "IN",
      duration: 152,
    },
    {
      title: "Inception",
      description: "سفر چندلایه و ذهن‌پیچ در دنیای رویاها.",
      poster: "/Images/movies/4.webp",
      videoUrl: "/Videos/4.mp4",
      rating: 9.3,
      topWeek: false,
      genre: ["Sci-Fi", "Action", "Adventure"],
      year: 2010,
      product: "IN",
      duration: 148,
    },
    {
      title: "Interstellar",
      description: "کاوشی فضایی درباره بقا و عشق.",
      poster: "/Images/movies/5.jpg",
      videoUrl: "/Videos/5.mp4",
      rating: 9.4,
      topWeek: false,
      genre: ["Sci-Fi", "Drama", "Adventure"],
      year: 2014,
      product: "IN",
      duration: 169,
    },
    {
      title: "Fight Club",
      description: "روایتی ضدسیستمی درباره هویت و مصرف‌گرایی.",
      poster: "/Images/movies/6.jpg",
      videoUrl: "/Videos/6.mp4",
      rating: 9.2,
      topWeek: false,
      genre: ["Drama"],
      year: 1999,
      product: "IN",
      duration: 139,
    },
    {
      title: "Forrest Gump",
      description: "زندگی مردی ساده‌دل که تاریخ را لمس می‌کند.",
      poster: "/Images/movies/7.jpg",
      videoUrl: "/Videos/7.mp4",
      rating: 9.1,
      topWeek: false,
      genre: ["Drama", "Romance"],
      year: 1994,
      product: "IN",
      duration: 142,
    },
    {
      title: "Pulp Fiction",
      description: "داستان‌های جنایی تارانتینو با ساختار غیرخطی.",
      poster: "/Images/movies/8.webp",
      videoUrl: "/Videos/8.mp4",
      rating: 9.0,
      topWeek: false,
      genre: ["Crime", "Drama"],
      year: 1994,
      product: "IN",
      duration: 154,
    },
    {
      title: "Gladiator",
      description: "روایت انتقام و افتخار در روم باستان.",
      poster: "/Images/movies/1.webp",
      videoUrl: "/Videos/9.mp4",
      rating: 8.8,
      topWeek: false,
      genre: ["Action", "Drama", "Adventure"],
      year: 2000,
      product: "IN",
      duration: 155,
    },
    {
      title: "The Matrix",
      description: "انقلابی در ژانر علمی‌تخیلی با مفهوم شبیه‌سازی.",
      poster: "/Images/movies/10.jpg",
      videoUrl: "/Videos/10.mp4",
      rating: 9.0,
      topWeek: true,
      genre: ["Sci-Fi", "Action"],
      year: 1999,
      product: "IN",
      duration: 136,
    },
    {
      title: "Se7en",
      description: "تعقیب قاتلی که قتل‌ها را بر اساس هفت گناه کبیره انجام می‌دهد.",
      poster: "/Images/movies/11.jpg",
      videoUrl: "/Videos/11.mp4",
      rating: 8.9,
      topWeek: false,
      genre: ["Crime", "Thriller", "Mystery"],
      year: 1995,
      product: "IN",
      duration: 127,
    },
    {
      title: "Whiplash",
      description: "رابطه پرتنش هنرجوی درام و استاد سختگیرش.",
      poster: "/Images/movies/12.jpg",
      videoUrl: "/Videos/12.mp4",
      rating: 8.7,
      topWeek: false,
      genre: ["Drama", "Music"],
      year: 2014,
      product: "IN",
      duration: 106,
    },
    {
      title: "The Social Network",
      description: "داستان شکل‌گیری فیسبوک و جاه‌طلبی.",
      poster: "/Images/movies/13.webp",
      videoUrl: "/Videos/13.mp4",
      rating: 8.5,
      topWeek: false,
      genre: ["Drama", "Biography"],
      year: 2010,
      product: "IN",
      duration: 120,
    },
    {
      title: "The Prestige",
      description: "رقابت وسواس‌گونه میان دو شعبده‌باز.",
      poster: "/Images/movies/14.webp",
      videoUrl: "/Videos/14.mp4",
      rating: 8.6,
      topWeek: false,
      genre: ["Drama", "Mystery", "Thriller"],
      year: 2006,
      product: "IN",
      duration: 130,
    },
    {
      title: "Parasite",
      description: "برخورد دو طبقه اجتماعی در داستانی هوشمندانه و تکان‌دهنده.",
      poster: "/Images/movies/15.webp",
      videoUrl: "/Videos/15.mp4",
      rating: 9.1,
      topWeek: true,
      genre: ["Drama", "Thriller"],
      year: 2019,
      product: "IN",
      duration: 132,
    },
    {
      title: "Joker",
      description: "سقوط تدریجی یک مرد تنها به دنیای جنون.",
      poster: "/Images/movies/1.webp",
      videoUrl: "/Videos/16.mp4",
      rating: 8.6,
      topWeek: false,
      genre: ["Crime", "Drama", "Thriller"],
      year: 2019,
      product: "IN",
      duration: 122,
    },
    {
      title: "Django Unchained",
      description: "انتقام برده‌ای آزادشده در وسترنی پرانرژی.",
      poster: "/Images/movies/17.webp",
      videoUrl: "/Videos/17.mp4",
      rating: 8.5,
      topWeek: false,
      genre: ["Western", "Drama"],
      year: 2012,
      product: "IN",
      duration: 165,
    },
    {
      title: "Mad Max: Fury Road",
      description: "اکشنی دیوانه‌وار در دنیای آخرالزمانی.",
      poster: "/Images/movies/18.webp",
      videoUrl: "/Videos/18.mp4",
      rating: 8.4,
      topWeek: false,
      genre: ["Action", "Adventure", "Sci-Fi"],
      year: 2015,
      product: "IN",
      duration: 120,
    },
    {
      title: "The Green Mile",
      description: "روایتی احساسی و ماورایی از بند اعدامی‌ها.",
      poster: "/Images/movies/19.webp",
      videoUrl: "/Videos/19.mp4",
      rating: 9.2,
      topWeek: true,
      genre: ["Drama", "Fantasy", "Crime"],
      year: 1999,
      product: "IN",
      duration: 189,
    },
    {
      title: "Blade Runner 2049",
      description: "جهانی تاریک درباره هویت و انسان‌بودن.",
      poster: "/Images/movies/20.webp",
      videoUrl: "/Videos/20.mp4",
      rating: 8.6,
      topWeek: false,
      genre: ["Sci-Fi", "Drama", "Mystery"],
      year: 2017,
      product: "IN",
      duration: 164,
    }, {
      title: "The Pianist",
      description: "داستان واقعی یک نوازنده پیانو در جنگ جهانی دوم.",
      poster: "/Images/movies/21.webp",
      videoUrl: "/Videos/21.mp4",
      rating: 9.0,
      topWeek: false,
      genre: ["Drama", "Biography", "War"],
      year: 2002,
      product: "IN",
      duration: 150,
    },
    {
      title: "The Silence of the Lambs",
      description: "تعقیب یک قاتل زنجیره‌ای با کمک هانیبال لکتر.",
      poster: "/Images/movies/22.webp",
      videoUrl: "/Videos/22.mp4",
      rating: 8.9,
      topWeek: true,
      genre: ["Crime", "Thriller"],
      year: 1991,
      product: "IN",
      duration: 118,
    },
    {
      title: "The Departed",
      description: "نفوذ پلیس و مافیا به درون یکدیگر.",
      poster: "/Images/movies/23.webp",
      videoUrl: "/Videos/23.mp4",
      rating: 8.8,
      topWeek: false,
      genre: ["Crime", "Drama", "Thriller"],
      year: 2006,
      product: "IN",
      duration: 151,
    },
    {
      title: "Shutter Island",
      description: "کارآگاهی که در جزیره‌ای اسرارآمیز به دنبال حقیقت می‌گردد.",
      poster: "/Images/movies/24.webp",
      videoUrl: "/Videos/24.mp4",
      rating: 8.7,
      topWeek: false,
      genre: ["Mystery", "Thriller"],
      year: 2010,
      product: "IN",
      duration: 138,
    },
    {
      title: "The Wolf of Wall Street",
      description: "داستان زندگی جنجالی جردن بلفورت.",
      poster: "/Images/movies/25.webp",
      videoUrl: "/Videos/25.mp4",
      rating: 8.6,
      topWeek: false,
      genre: ["Comedy", "Biography", "Crime"],
      year: 2013,
      product: "IN",
      duration: 180,
    },
    {
      title: "Oppenheimer",
      description: "زندگی رابرت اوپنهایمر و ساخت بمب اتم.",
      poster: "/Images/movies/26.webp",
      videoUrl: "/Videos/26.mp4",
      rating: 8.9,
      topWeek: true,
      genre: ["Biography", "Drama", "History"],
      year: 2023,
      product: "IN",
      duration: 180,
    },
    {
      title: "Dune",
      description: "حماسه‌ای علمی‌تخیلی در سیاره آراکیس.",
      poster: "/Images/movies/27.webp",
      videoUrl: "/Videos/27.mp4",
      rating: 8.5,
      topWeek: false,
      genre: ["Sci-Fi", "Adventure"],
      year: 2021,
      product: "IN",
      duration: 155,
    },
    {
      title: "Dune: Part Two",
      description: "ادامه نبرد پل آتریدیز برای سرنوشت آراکیس.",
      poster: "/Images/movies/28.webp",
      videoUrl: "/Videos/28.mp4",
      rating: 9.1,
      topWeek: true,
      genre: ["Sci-Fi", "Adventure"],
      year: 2024,
      product: "IN",
      duration: 166,
    },
    {
      title: "Avengers: Endgame",
      description: "نبرد نهایی انتقام‌جویان با تانوس.",
      poster: "/Images/movies/29.webp",
      videoUrl: "/Videos/29.mp4",
      rating: 8.7,
      topWeek: false,
      genre: ["Action", "Adventure", "Sci-Fi"],
      year: 2019,
      product: "IN",
      duration: 181,
    },
    {
      title: "Spider-Man: No Way Home",
      description: "باز شدن دروازه مولتی‌ورس برای مرد عنکبوتی.",
      poster: "/Images/movies/30.webp",
      videoUrl: "/Videos/30.mp4",
      rating: 8.5,
      topWeek: false,
      genre: ["Action", "Adventure"],
      year: 2021,
      product: "IN",
      duration: 148,
    },
    {
      title: "The Lord of the Rings: The Fellowship of the Ring",
      description: "آغاز سفر فرودو برای نابودی حلقه.",
      poster: "/Images/movies/31.webp",
      videoUrl: "/Videos/31.mp4",
      rating: 9.1,
      topWeek: true,
      genre: ["Adventure", "Fantasy"],
      year: 2001,
      product: "IN",
      duration: 178,
    },
    {
      title: "The Lord of the Rings: The Two Towers",
      description: "ادامه نبرد سرزمین میانه.",
      poster: "/Images/movies/32.webp",
      videoUrl: "/Videos/32.mp4",
      rating: 9.0,
      topWeek: false,
      genre: ["Adventure", "Fantasy"],
      year: 2002,
      product: "IN",
      duration: 179,
    },
    {
      title: "The Lord of the Rings: The Return of the King",
      description: "پایان حماسه حلقه یگانه.",
      poster: "/Images/movies/33.webp",
      videoUrl: "/Videos/33.mp4",
      rating: 9.3,
      topWeek: true,
      genre: ["Adventure", "Fantasy"],
      year: 2003,
      product: "IN",
      duration: 201,
    },
    {
      title: "John Wick",
      description: "قاتل افسانه‌ای برای انتقام بازمی‌گردد.",
      poster: "/Images/movies/34.webp",
      videoUrl: "/Videos/34.mp4",
      rating: 8.4,
      topWeek: false,
      genre: ["Action", "Crime"],
      year: 2014,
      product: "IN",
      duration: 101,
    },
    {
      title: "John Wick: Chapter 4",
      description: "نبرد نهایی جان ویک با انجمن قاتلان.",
      poster: "/Images/movies/35.webp",
      videoUrl: "/Videos/35.mp4",
      rating: 8.8,
      topWeek: true,
      genre: ["Action", "Thriller"],
      year: 2023,
      product: "IN",
      duration: 169,
    }, {
      title: "The Batman",
      description: "بتمن در تعقیب قاتلی مرموز به نام ریدلر.",
      poster: "/Images/movies/36.webp",
      videoUrl: "/Videos/36.mp4",
      rating: 8.5,
      topWeek: false,
      genre: ["Action", "Crime", "Drama"],
      year: 2022,
      product: "IN",
      duration: 176,
    },
    {
      title: "Logan",
      description: "آخرین ماجراجویی ولورین در دنیایی تاریک.",
      poster: "/Images/movies/37.webp",
      videoUrl: "/Videos/37.mp4",
      rating: 8.7,
      topWeek: false,
      genre: ["Action", "Drama", "Sci-Fi"],
      year: 2017,
      product: "IN",
      duration: 137,
    },
    {
      title: "Deadpool",
      description: "ابرقهرمانی شوخ‌طبع که به دنبال انتقام است.",
      poster: "/Images/movies/38.webp",
      videoUrl: "/Videos/38.mp4",
      rating: 8.2,
      topWeek: false,
      genre: ["Action", "Comedy"],
      year: 2016,
      product: "IN",
      duration: 108,
    },
    {
      title: "Deadpool 2",
      description: "ماجراجویی جدید ددپول با تیم X-Force.",
      poster: "/Images/movies/39.webp",
      videoUrl: "/Videos/39.mp4",
      rating: 8.1,
      topWeek: false,
      genre: ["Action", "Comedy"],
      year: 2018,
      product: "IN",
      duration: 119,
    },
    {
      title: "Top Gun: Maverick",
      description: "بازگشت ماوریک برای آموزش نسل جدید خلبانان.",
      poster: "/Images/movies/40.webp",
      videoUrl: "/Videos/40.mp4",
      rating: 8.8,
      topWeek: true,
      genre: ["Action", "Drama"],
      year: 2022,
      product: "IN",
      duration: 130,
    },
    {
      title: "1917",
      description: "ماموریتی نفس‌گیر در میانه جنگ جهانی اول.",
      poster: "/Images/movies/41.webp",
      videoUrl: "/Videos/41.mp4",
      rating: 8.6,
      topWeek: false,
      genre: ["War", "Drama"],
      year: 2019,
      product: "IN",
      duration: 119,
    },
    {
      title: "Saving Private Ryan",
      description: "نجات یک سرباز در بحبوحه جنگ جهانی دوم.",
      poster: "/Images/movies/42.webp",
      videoUrl: "/Videos/42.mp4",
      rating: 9.0,
      topWeek: true,
      genre: ["War", "Drama"],
      year: 1998,
      product: "IN",
      duration: 169,
    },
    {
      title: "The Truman Show",
      description: "مردی متوجه می‌شود تمام زندگی‌اش یک نمایش تلویزیونی بوده است.",
      poster: "/Images/movies/43.webp",
      videoUrl: "/Videos/43.mp4",
      rating: 8.9,
      topWeek: false,
      genre: ["Drama", "Sci-Fi"],
      year: 1998,
      product: "IN",
      duration: 103,
    },
    {
      title: "Catch Me If You Can",
      description: "داستان واقعی کلاهبرداری نابغه و مأمور FBI.",
      poster: "/Images/movies/44.webp",
      videoUrl: "/Videos/44.mp4",
      rating: 8.7,
      topWeek: false,
      genre: ["Biography", "Crime"],
      year: 2002,
      product: "IN",
      duration: 141,
    },
    {
      title: "The Revenant",
      description: "نبردی برای بقا و انتقام در طبیعت وحشی.",
      poster: "/Images/movies/45.webp",
      videoUrl: "/Videos/45.mp4",
      rating: 8.5,
      topWeek: false,
      genre: ["Adventure", "Drama"],
      year: 2015,
      product: "IN",
      duration: 156,
    },
    {
      title: "No Country for Old Men",
      description: "تعقیب مرگبار بر سر یک کیف پول پر از پول.",
      poster: "/Images/movies/46.webp",
      videoUrl: "/Videos/46.mp4",
      rating: 8.8,
      topWeek: false,
      genre: ["Crime", "Thriller"],
      year: 2007,
      product: "IN",
      duration: 122,
    },
    {
      title: "Prisoners",
      description: "پدری برای پیدا کردن دخترش دست به هر کاری می‌زند.",
      poster: "/Images/movies/47.webp",
      videoUrl: "/Videos/47.mp4",
      rating: 8.7,
      topWeek: true,
      genre: ["Crime", "Mystery", "Thriller"],
      year: 2013,
      product: "IN",
      duration: 153,
    },
    {
      title: "Gone Girl",
      description: "ناپدید شدن همسر و رازهای تاریک یک ازدواج.",
      poster: "/Images/movies/48.webp",
      videoUrl: "/Videos/48.mp4",
      rating: 8.6,
      topWeek: false,
      genre: ["Mystery", "Thriller"],
      year: 2014,
      product: "IN",
      duration: 149,
    },
    {
      title: "The Irishman",
      description: "روایت زندگی یک آدمکش مافیایی در چند دهه.",
      poster: "/Images/movies/49.webp",
      videoUrl: "/Videos/49.mp4",
      rating: 8.3,
      topWeek: false,
      genre: ["Crime", "Drama"],
      year: 2019,
      product: "IN",
      duration: 209,
    },
    {
      title: "The Imitation Game",
      description: "زندگی آلن تورینگ و شکستن رمز انیگما.",
      poster: "/Images/movies/50.webp",
      videoUrl: "/Videos/50.mp4",
      rating: 8.6,
      topWeek: false,
      genre: ["Biography", "Drama"],
      year: 2014,
      product: "IN",
      duration: 114,
    }, {
      title: "The Lion King",
      description: "ماجرای سیمبا برای بازپس‌گیری سرزمینش.",
      poster: "/Images/movies/51.webp",
      videoUrl: "/Videos/51.mp4",
      rating: 8.9,
      topWeek: true,
      genre: ["Animation", "Adventure", "Drama"],
      year: 1994,
      product: "IN",
      duration: 88,
    },
    {
      title: "Spirited Away",
      description: "دختری وارد دنیای اسرارآمیز ارواح می‌شود.",
      poster: "/Images/movies/52.webp",
      videoUrl: "/Videos/52.mp4",
      rating: 9.1,
      topWeek: true,
      genre: ["Animation", "Fantasy", "Adventure"],
      year: 2001,
      product: "IN",
      duration: 125,
    },
    {
      title: "Your Name",
      description: "داستانی عاشقانه با پیچشی فراطبیعی.",
      poster: "/Images/movies/53.webp",
      videoUrl: "/Videos/53.mp4",
      rating: 8.8,
      topWeek: false,
      genre: ["Animation", "Drama", "Romance"],
      year: 2016,
      product: "IN",
      duration: 106,
    },
    {
      title: "Coco",
      description: "سفری به دنیای مردگان با محوریت خانواده و موسیقی.",
      poster: "/Images/movies/54.webp",
      videoUrl: "/Videos/54.mp4",
      rating: 8.8,
      topWeek: false,
      genre: ["Animation", "Adventure", "Family"],
      year: 2017,
      product: "IN",
      duration: 105,
    },
    {
      title: "Soul",
      description: "داستانی درباره هدف زندگی و ارزش لحظه‌ها.",
      poster: "/Images/movies/55.webp",
      videoUrl: "/Videos/55.mp4",
      rating: 8.5,
      topWeek: false,
      genre: ["Animation", "Comedy", "Fantasy"],
      year: 2020,
      product: "IN",
      duration: 100,
    },
    {
      title: "Toy Story",
      description: "اسباب‌بازی‌هایی که وقتی کسی نیست جان می‌گیرند.",
      poster: "/Images/movies/56.webp",
      videoUrl: "/Videos/56.mp4",
      rating: 8.3,
      topWeek: false,
      genre: ["Animation", "Adventure", "Comedy"],
      year: 1995,
      product: "IN",
      duration: 81,
    },
    {
      title: "Inside Out",
      description: "احساسات یک دختر نوجوان شخصیت پیدا می‌کنند.",
      poster: "/Images/movies/57.webp",
      videoUrl: "/Videos/57.mp4",
      rating: 8.6,
      topWeek: false,
      genre: ["Animation", "Comedy", "Family"],
      year: 2015,
      product: "IN",
      duration: 95,
    },
    {
      title: "The Grand Budapest Hotel",
      description: "ماجراهای عجیب مدیر یک هتل لوکس.",
      poster: "/Images/movies/58.webp",
      videoUrl: "/Videos/58.mp4",
      rating: 8.4,
      topWeek: false,
      genre: ["Comedy", "Adventure"],
      year: 2014,
      product: "IN",
      duration: 99,
    },
    {
      title: "La La Land",
      description: "عشق، موسیقی و رویاهای هالیوودی.",
      poster: "/Images/movies/59.webp",
      videoUrl: "/Videos/59.mp4",
      rating: 8.5,
      topWeek: false,
      genre: ["Drama", "Music", "Romance"],
      year: 2016,
      product: "IN",
      duration: 128,
    },
    {
      title: "A Beautiful Mind",
      description: "زندگی ریاضیدان نابغه جان نش.",
      poster: "/Images/movies/60.webp",
      videoUrl: "/Videos/60.mp4",
      rating: 8.7,
      topWeek: false,
      genre: ["Biography", "Drama"],
      year: 2001,
      product: "IN",
      duration: 135,
    },
    {
      title: "The Curious Case of Benjamin Button",
      description: "مردی که برعکس پیر می‌شود.",
      poster: "/Images/movies/61.webp",
      videoUrl: "/Videos/61.mp4",
      rating: 8.4,
      topWeek: false,
      genre: ["Drama", "Fantasy", "Romance"],
      year: 2008,
      product: "IN",
      duration: 166,
    },
    {
      title: "The Terminal",
      description: "مسافری که در فرودگاه گیر می‌افتد.",
      poster: "/Images/movies/62.webp",
      videoUrl: "/Videos/62.mp4",
      rating: 8.2,
      topWeek: false,
      genre: ["Comedy", "Drama"],
      year: 2004,
      product: "IN",
      duration: 128,
    },
    {
      title: "Her",
      description: "رابطه‌ای عاشقانه میان انسان و هوش مصنوعی.",
      poster: "/Images/movies/63.webp",
      videoUrl: "/Videos/63.mp4",
      rating: 8.3,
      topWeek: false,
      genre: ["Drama", "Romance", "Sci-Fi"],
      year: 2013,
      product: "IN",
      duration: 126,
    },
    {
      title: "The Truman Show",
      description: "مردی که متوجه می‌شود تمام زندگی‌اش یک برنامه تلویزیونی بوده است.",
      poster: "/Images/movies/64.webp",
      videoUrl: "/Videos/64.mp4",
      rating: 8.9,
      topWeek: true,
      genre: ["Drama", "Sci-Fi"],
      year: 1998,
      product: "IN",
      duration: 103,
    },
    {
      title: "Everything Everywhere All at Once",
      description: "ماجرایی دیوانه‌وار میان دنیاهای موازی.",
      poster: "/Images/movies/65.webp",
      videoUrl: "/Videos/65.mp4",
      rating: 8.8,
      topWeek: true,
      genre: ["Action", "Adventure", "Sci-Fi"],
      year: 2022,
      product: "IN",
      duration: 139,
    },
  ];



  // 5. ذخیره دیتا
  Movie.insertMany(sampleMovies)
    .then(() => console.log('✅ Users inserted successfully!'))
    // .then(() => Movie.insertMany(sampleMovies))
    // .then(() => console.log('✅ Movies inserted successfully!'))
    .then(() => {
      console.log('🎉 All done! Check your MongoDB Compass to see the data.');
      process.exit(); // برنامه رو می‌بنده
    })
    .catch((err: any) => {

      console.error('❌ Error:', err);
      process.exit(1);
    });

});
